services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      - RATE_LIMIT_IP=${RATE_LIMIT_IP}
      - RATE_LIMIT_TOKEN=${RATE_LIMIT_TOKEN}
      - BAN_DURATION=${BAN_DURATION}
    depends_on:
      - redis
